default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: catalog_nestle_development

test:
  <<: *default
  database: catalog_nestle_test

production:
  adapter: postgresql
  encoding: unicode
  database: catalogo
  pool: 5
  username: catalog_nestle
  password: 159357

